// icons.ts
// Single registry for every Lucide icon used in the app.
// Import icons through the Icon component — not from lucide-react directly.
// --------------------------------------------------

import {
  Binary,
  BookOpen,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  CircleAlert,
  CircleX,
  CloudCheck,
  Code,
  Crop,
  Filter,
  Focus,
  Globe,
  Info,
  LayoutGrid,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Undo2,
  Unlock,
  Redo2,
  Maximize2,
  Minimize2,
  Minus,
  PanelRight,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Sparkles,
  StickyNote,
  Trash2,
  Type,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const icons = {
  binary: Binary,
  bookOpen: BookOpen,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  circleAlert: CircleAlert,
  circleX: CircleX,
  cloudCheck: CloudCheck,
  code: Code,
  crop: Crop,
  filter: Filter,
  focus: Focus,
  globe: Globe,
  info: Info,
  layoutGrid: LayoutGrid,
  loaderCircle: LoaderCircle,
  lock: Lock,
  logIn: LogIn,
  logOut: LogOut,
  maximize2: Maximize2,
  minimize2: Minimize2,
  minus: Minus,
  panelRight: PanelRight,
  plus: Plus,
  refreshCw: RefreshCw,
  redo: Redo2,
  search: Search,
  settings: Settings,
  sparkles: Sparkles,
  stickyNote: StickyNote,
  trash2: Trash2,
  type: Type,
  undo: Undo2,
  unlock: Unlock,
  x: X,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export const iconNames = Object.keys(icons) as IconName[];
